// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-header/DailyDarshan.tsx": () => import("../components/mockups/home-header/DailyDarshan.tsx"),
  "./components/mockups/home-header/SacredManuscript.tsx": () => import("../components/mockups/home-header/SacredManuscript.tsx"),
  "./components/mockups/home-header/TempleThreshold.tsx": () => import("../components/mockups/home-header/TempleThreshold.tsx")
};
